version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    container_name: elasticsearch
    networks: 
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    depends_on: 
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    container_name: kibana
    networks:
      - elastic

volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic: 
    driver: bridge